name: Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on:  [ubuntu-latest]
    strategy:
      matrix:
        jvm: [8, 11, 14]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.0
        with:
          fetch-depth: 50
      - name: Gradle Cache
        id: gradle-cache
        uses: actions/cache@v2.0.0
        with:
          path: ~/.gradle/caches
          key: jdk${{ matrix.jvm }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            jdk${{ matrix.jvm }}-gradle-
      - name: Set up JDK ${{ matrix.jvm }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jvm }}
      - name: Gradle Test
        run: |
          chmod +x ./gradlew
          ./gradlew test -x javadoc